name: scikit_learn_workshop
channels:
  - districtdatalabs
  - conda-forge
  - defaults
dependencies:
  - atomicwrites=1.3.0=py_0
  - attrs=19.1.0=py_0
  - backcall=0.1.0=py_0
  - blas=1.0=mkl
  - bleach=3.1.0=py_0
  - ca-certificates=2019.6.16=hecc5488_0
  - certifi=2019.6.16=py37_1
  - colorama=0.4.1=py_0
  - cycler=0.10.0=py_1
  - decorator=4.4.0=py_0
  - defusedxml=0.5.0=py_1
  - eli5=0.9.0=py_0
  - entrypoints=0.3=py37_1000
  - freetype=2.10.0=h563cfd7_1
  - graphviz=2.38.0=h6538335_1011
  - icc_rt=2019.0.0=h0cc432a_1
  - icu=64.2=he025d50_0
  - importlib_metadata=0.18=py37_0
  - intel-openmp=2019.4=245
  - ipykernel=5.1.2=py37h5ca1d4c_0
  - ipython=7.7.0=py37h5ca1d4c_0
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.5.1=py_0
  - jedi=0.15.1=py37_0
  - jinja2=2.10.1=py_0
  - joblib=0.13.2=py_0
  - jpeg=9c=hfa6e2cd_1001
  - jsonschema=3.0.2=py37_0
  - jupyter=1.0.0=py_2
  - jupyter_client=5.3.1=py_0
  - jupyter_console=6.0.0=py_0
  - jupyter_core=4.4.0=py_0
  - kiwisolver=1.1.0=py37he980bc4_0
  - libblas=3.8.0=12_mkl
  - libcblas=3.8.0=12_mkl
  - liblapack=3.8.0=12_mkl
  - libpng=1.6.37=h7602738_0
  - libsodium=1.0.17=h2fa13f4_0
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markupsafe=1.1.1=py37hfa6e2cd_0
  - matplotlib=3.1.1=py37_1
  - matplotlib-base=3.1.1=py37h2852a4a_1
  - mistune=0.8.4=py37hfa6e2cd_1000
  - mkl=2019.4=245
  - mkl-service=2.1.0=py37hfa6e2cd_0
  - mlxtend=0.17.0=py_0
  - more-itertools=7.2.0=py_0
  - msys2-conda-epoch=20160418=1
  - nbconvert=5.6.0=py_0
  - nbformat=4.4.0=py_1
  - notebook=6.0.0=py37_0
  - numpy=1.17.0=py37hc71023c_0
  - openssl=1.1.1c=hfa6e2cd_0
  - packaging=19.0=py_0
  - pandas=0.25.0=py37he350917_0
  - pandoc=2.7.3=0
  - pandocfilters=1.4.2=py_1
  - parso=0.5.1=py_0
  - patsy=0.5.1=py_0
  - pickleshare=0.7.5=py37_1000
  - pip=19.2.2=py37_0
  - pluggy=0.12.0=py_0
  - prometheus_client=0.7.1=py_0
  - prompt_toolkit=2.0.9=py_0
  - py=1.8.0=py_0
  - pygments=2.4.2=py_0
  - pyparsing=2.4.2=py_0
  - pyqt=5.9.2=py37h6538335_2
  - pyrsistent=0.15.4=py37hfa6e2cd_0
  - pytest=5.0.1=py37_1
  - pytest-runner=5.1=py_0
  - python=3.7.3=h510b542_1
  - python-dateutil=2.8.0=py_0
  - python-graphviz=0.11.1=py_1
  - pytz=2019.2=py_0
  - pywinpty=0.5.5=py37_1000
  - pyzmq=18.0.2=py37h16f9016_2
  - qt=5.9.7=h506e8af_3
  - qtconsole=4.5.2=py_0
  - scikit-learn=0.21.3=py37h7208079_0
  - scipy=1.3.0=py37h29ff71c_0
  - seaborn=0.9.0=py_1
  - send2trash=1.5.0=py_0
  - setuptools=41.0.1=py37_0
  - singledispatch=3.4.0.3=py37_1000
  - sip=4.19.8=py37h6538335_1000
  - six=1.12.0=py37_1000
  - sqlite=3.29.0=hfa6e2cd_0
  - statsmodels=0.10.1=py37hfa6e2cd_0
  - tabulate=0.8.3=py_0
  - terminado=0.8.2=py37_0
  - testpath=0.4.2=py_1001
  - tornado=6.0.3=py37hfa6e2cd_0
  - traitlets=4.3.2=py37_1000
  - typing=3.6.4=py37_0
  - vc=14.1=h0510ff6_4
  - vs2015_runtime=14.15.26706=h3a45250_4
  - wcwidth=0.1.7=py_1
  - webencodings=0.5.1=py_1
  - wheel=0.33.4=py37_0
  - widgetsnbextension=3.5.1=py37_0
  - wincertstore=0.2=py37_1002
  - winpty=0.4.3=4
  - yellowbrick=0.9.1=py37_0
  - zeromq=4.3.2=h6538335_2
  - zipp=0.5.2=py_0
  - zlib=1.2.11=h2fa13f4_1005
prefix: C:\Users\timvi\Miniconda3\envs\scikit_learn_workshop

